### ISSUE TITLE
Pools sharing relay connection?

### ISSUE THREAD

**Issue by antonioconselheiro** [soapbox-pub/nostrify#1]
If I have two relays configured in my pool: `a` and `b`, and I enter in a profile with `b` and `c` relays in relay list, would be correct create a pool reusing existing `b` connection?

Reusing connections is a good practice? If it is, I would like to suggest another pools model, like `NDerivatedPool` and/or `NExtendedPool`, they should not be able to close inherited connections and reuse existing connections.

**Comment by alexgleason** [comment]
Reusing pools is the best practice. NPool already does this. It's not perfect, but it at least reuses the connection.

If you want a different pool behavior I suggest creating a new class that implements the NRelay interface.

**Comment by antonioconselheiro** [comment]
Understood
