### ISSUE TITLE
relay count method didn't throw error

### ISSUE THREAD

**Issue by antonioconselheiro** [soapbox-pub/nostrify#3]
Strfry doesn't support NIP-45 count, it throws NOTICE when unkown filter is given.
Relay count method from nostrify didn't listen to this NOTICE and keep the promise waiting forever.

![image](https://github.com/user-attachments/assets/9d0160a4-1b75-42fa-ae72-062d0a06fc82)

**Comment by antonioconselheiro** [comment]
moved to an issue into strfry repo

**Comment by alexgleason** [comment]
I did not see until now that NIP-45 actually supports the `CLOSED` verb, so I added support for it in NRelay1 here: https://gitlab.com/soapbox-pub/nostrify/-/merge_requests/105

Released in [`@nostrify/nostrify@0.36.1`](https://jsr.io/@nostrify/nostrify@0.36.1)
